# Server
server.port=8080

# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/explore-with-me-main
spring.datasource.username=main
spring.datasource.password=main

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Stats Server URL
stats-server.url=http://localhost:9090

# Logging
logging.level.ru.practicum=DEBUG
logging.level.org.springframework.web=DEBUG